### DISCUSSION TITLE
Add basic yaml examples

### DISCUSSION THREAD

**Discussion by mDubovsky** [pilotak/eth-io#14] [Ideas]
For people not so versed in the esphome ecosystem it would be beneficial to add yaml examples such as (but not limited to):

- configuration for ethernet
- configuration for wifi
- 2 daisy chained modules
- basic functionality like double click / long press

This can be added to readme and/or wiki

**Comment by pilotak** [comment]
another option is to show is the gang switch intead of button

```yaml
binary_sensor:
  - platform: gpio
    id: in1
    pin:
      pcf8574: in_hub1
      number: 7
      mode: INPUT
      inverted: True
    filters:
      - delayed_on: 3ms
      - delayed_off: 3ms
    on_press:
      then:
        - switch.turn_on: output1
    on_release:
      then:
        - switch.turn_off: output1
```
